name: Rust

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout
        uses: actions/checkout@v4

      - name: Setup Rust
        run: rustup update stable && rustup default stable

      - name: Build
        run: cargo build --release --verbose

      - name: Prepare artifacts
        run: |
          mkdir artifacts
          cp -r target/release/autorunner artifacts/
          cp -r docker artifacts/
          cp -r scripts artifacts/
          cd artifacts && zip -r autorunner.zip .

      - name: Copy artifacts to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AUTORUNNER_HOST }}
          username: ${{ secrets.AUTORUNNER_USERNAME }}
          key: ${{ secrets.AUTORUNNER_KEY }}
          port: 22
          source: ./artifacts/autorunner.zip
          target: /home/ubuntu/autorunner/

      - name: Deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AUTORUNNER_HOST }}
          username: ${{ secrets.AUTORUNNER_USERNAME }}
          key: ${{ secrets.AUTORUNNER_KEY }}
          port: 22
          script: |
            cd ~/autorunner
            rm -rf docker
            rm -rf scripts
            rm -rf autorunner
            unzip artifacts/autorunner.zip
            rm -rf artifacts
            chmod +x ./scripts/daemon.sh
            ./scripts/daemon.sh
            
